# backend/database/repository.py
#
# Data access layer — all SQL operations go through these functions.
#
# REPOSITORY PATTERN (from Decoupling-and-Law-of-Demeter.md, Pragmatic Programmer wiki):
#   "A module should not reach through its immediate neighbor to access another layer."
#   Nodes and agents do NOT import SQLAlchemy or write SQL directly.
#   They call save_review(), get_review(), list_findings_for_repo().
#   The repository is the ONLY place that speaks SQLAlchemy to the database.
#   This means swapping Postgres for a different store only requires changing this file.
#
# TRANSACTION SCOPE:
# (From Storage-Engines.md wiki, "Write-Ahead Log and Transactions"):
#   "A write that spans multiple tables must succeed atomically or not at all."
#   save_review() writes PRReviewRecord + all FindingRecords in ONE transaction.
#   If any insert fails, the whole transaction rolls back — no partial state.
#   We use session.begin() as the transaction scope explicitly.
#
# ASYNC PATTERNS:
# (From Storage-Engines.md wiki):
#   "await session.execute() for reads, await session.flush() before accessing IDs,
#    await session.commit() to finalize writes."
#   We await every database call. Never use synchronous SQLAlchemy in async context.
#
# DEPENDENCY DIRECTION CHECK:
#   repository.py imports from: backend.database.postgres (session), backend.database.models
#   repository.py does NOT import from: agents, orchestrator, tools
#   This is correct — repository is at the tools/memory layer.

import logging
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.database.models import FindingRecord, PRReviewRecord

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# SEVERITY ORDERING
#
# Used by list_findings_for_repo() to filter by minimum severity.
# "Give me all findings with severity >= HIGH" means critical and high.
# We express this as a ranked list rather than a DB ENUM comparison.
# ---------------------------------------------------------------------------
_SEVERITY_RANK: dict[str, int] = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
}


# ---------------------------------------------------------------------------
# save_review()
#
# The main write path. Called by the orchestrator after a review completes.
# Writes one PRReviewRecord + N FindingRecords in one atomic transaction.
# ---------------------------------------------------------------------------
async def save_review(
    session: AsyncSession,
    *,
    review_id: str,
    repo_full_name: str,
    pr_number: int,
    pr_title: str,
    head_commit_sha: str,
    pr_diff: str,
    verdict: str | None,
    status: str,
    overall_confidence: float,
    needs_human_review: bool,
    human_review_reason: str,
    findings: list[dict[str, Any]],
    github_review_id: int | None = None,
) -> PRReviewRecord:
    """
    Persists a completed PR review and all its findings atomically.

    ATOMICITY (from Storage-Engines.md wiki, "Transactions"):
    The PRReviewRecord and all FindingRecords are written in a single
    transaction. Either everything is committed, or nothing is.
    This prevents orphaned FindingRecords without a parent review.

    ORDERING CONSTRAINT (from DDIA / Transactions-and-Isolation wiki):
    "Only write review_id to Postgres AFTER GitHub confirms the review
    was accepted (2xx)."
    -> github_review_id is the ID returned by the GitHub API after a
       successful POST /pulls/{n}/reviews. It is passed here by the
       post_review node AFTER the GitHub call succeeds.
    -> If the GitHub call fails, this function is never called.
       No partial state: either both GitHub + Postgres succeed, or
       the Postgres row is never written (the review_id stays absent).
    -> Callers pass github_review_id=None for HITL-routed reviews
       (those were never posted to GitHub).

    Args:
        session:             SQLAlchemy AsyncSession (from get_db() dependency)
        review_id:           UUID string for this review (generated by orchestrator)
        repo_full_name:      "owner/repo" format
        pr_number:           GitHub PR number
        pr_title:            PR title at review time
        head_commit_sha:     Git commit SHA
        pr_diff:             Full diff text (used to compute diff_hash)
        verdict:             "approve" | "request_changes" | "needs_human_review" | None
        status:              ReviewStatus value as string
        overall_confidence:  Weighted average confidence (0.0 to 1.0)
        needs_human_review:  True if routed to HITL queue
        human_review_reason: Why it went to HITL (empty string if not)
        findings:            List of finding dicts from agent_results state.
                             Each dict must have: agent_type, severity, category,
                             summary. Optional: file_path, line_start, line_end,
                             suggestion, confidence.
        github_review_id:    GitHub's integer review ID from the API response.
                             None for HITL-routed reviews (not posted to GitHub).

    Returns:
        The persisted PRReviewRecord (with findings loaded via selectin).

    Raises:
        SQLAlchemyError on database failure (caller handles retry/logging).
    """
    now = datetime.now(timezone.utc)

    # Step 1: Build the PRReviewRecord ORM object
    review = PRReviewRecord(
        id=review_id,
        repo_full_name=repo_full_name,
        pr_number=pr_number,
        pr_title=pr_title,
        head_commit_sha=head_commit_sha,
        diff_hash=PRReviewRecord.compute_diff_hash(pr_diff),
        verdict=verdict,
        status=status,
        overall_confidence=overall_confidence,
        needs_human_review=1 if needs_human_review else 0,
        human_review_reason=human_review_reason,
        # github_review_id is populated AFTER a successful GitHub API post.
        # None for HITL-routed reviews that were never sent to GitHub.
        # WIKI: DDIA / Transactions-and-Isolation
        #   "Atomicity: only write this ID after GitHub confirms the review."
        github_review_id=github_review_id,
        created_at=now,
        updated_at=now,
    )

    # Step 2: Build FindingRecord objects for each finding
    finding_records: list[FindingRecord] = []
    for f in findings:
        finding_records.append(FindingRecord(
            id=str(uuid.uuid4()),
            review_id=review_id,
            repo_full_name=repo_full_name,      # denormalized (see models.py comment)
            agent_type=f.get("agent_type", "unknown"),
            severity=f.get("severity", "low"),
            category=f.get("category", "quality"),
            summary=f.get("summary", ""),
            file_path=f.get("file_path"),        # None is fine (nullable column)
            line_start=f.get("line_start"),
            line_end=f.get("line_end"),
            suggestion=f.get("suggestion"),
            confidence=float(f.get("confidence", 0.5)),
            created_at=now,
        ))

    # Step 3: Write everything in one atomic transaction
    # (From Storage-Engines.md wiki: "writes that span multiple tables must be atomic")
    async with session.begin():
        session.add(review)
        session.add_all(finding_records)
        # flush() forces SQL INSERT statements to execute within the transaction,
        # making IDs and constraints available for validation before commit.
        await session.flush()

    logger.info(
        "save_review | review_id=%s repo=%s pr=%d findings=%d status=%s",
        review_id, repo_full_name, pr_number, len(findings), status,
    )

    return review


# ---------------------------------------------------------------------------
# get_review()
#
# The main read path for a single review by ID.
# ---------------------------------------------------------------------------
async def get_review(
    session: AsyncSession,
    review_id: str,
) -> PRReviewRecord | None:
    """
    Fetches a single PRReviewRecord by its UUID.

    Returns None if not found (standard repository pattern — callers
    check for None rather than catching a NotFound exception).

    Findings are automatically loaded via selectin (defined on the model).
    No second query call needed — SQLAlchemy handles it.

    Args:
        session:   SQLAlchemy AsyncSession
        review_id: UUID string of the review to fetch

    Returns:
        PRReviewRecord with findings loaded, or None if not found.
    """
    result = await session.execute(
        select(PRReviewRecord).where(PRReviewRecord.id == review_id)
    )
    review = result.scalar_one_or_none()

    if review is None:
        logger.debug("get_review | not_found | review_id=%s", review_id)
    else:
        logger.debug(
            "get_review | found | review_id=%s findings=%d",
            review_id, len(review.findings),
        )

    return review


# ---------------------------------------------------------------------------
# list_findings_for_repo()
#
# Analytical query: "show me all HIGH+ findings for this repo."
# Used by the dashboard and reporting APIs.
# ---------------------------------------------------------------------------
async def list_findings_for_repo(
    session: AsyncSession,
    repo_full_name: str,
    min_severity: str = "high",
    limit: int = 100,
    offset: int = 0,
) -> list[FindingRecord]:
    """
    Returns findings for a repo filtered by minimum severity.

    This is the hot analytical query path.
    Uses the composite index (ix_finding_repo_severity) defined in models.py:
      WHERE repo_full_name = ? AND severity IN (...)
    Without the index: full table scan over all findings.
    With the index: index seek on repo_full_name, then filter severity.
    (Storage-Engines.md: "Index the columns you filter on, in filter order.")

    Args:
        session:        SQLAlchemy AsyncSession
        repo_full_name: "owner/repo" string to filter by
        min_severity:   Minimum severity to include. Default "high" means
                        return "critical" and "high" findings only.
                        Pass "low" to return all findings.
        limit:          Max rows to return (pagination).
        offset:         Row offset (pagination).

    Returns:
        List of FindingRecord objects, ordered by severity (critical first).
    """
    # Determine which severity values to include based on min_severity rank
    min_rank = _SEVERITY_RANK.get(min_severity.lower(), 1)  # default: high (rank 1)
    included_severities = [
        sev for sev, rank in _SEVERITY_RANK.items()
        if rank <= min_rank
    ]

    if not included_severities:
        logger.warning(
            "list_findings_for_repo | unknown min_severity=%s | returning empty",
            min_severity,
        )
        return []

    result = await session.execute(
        select(FindingRecord)
        .where(
            FindingRecord.repo_full_name == repo_full_name,
            FindingRecord.severity.in_(included_severities),
        )
        .order_by(FindingRecord.created_at.desc())
        .limit(limit)
        .offset(offset)
    )

    findings = list(result.scalars().all())

    logger.debug(
        "list_findings_for_repo | repo=%s min_severity=%s found=%d",
        repo_full_name, min_severity, len(findings),
    )

    return findings


# ---------------------------------------------------------------------------
# list_reviews()
#
# Paginated read path for the GET /api/v1/reviews endpoint.
# ---------------------------------------------------------------------------
async def list_reviews(
    session: AsyncSession,
    *,
    repo_full_name: str | None = None,
    status: str | None = None,
    limit: int = 50,
    offset: int = 0,
) -> tuple[list[PRReviewRecord], int]:
    """
    Returns a paginated list of PRReviewRecords with an accurate total count.

    PERFORMANCE NOTE (from Storage-Engines.md wiki, "Index Design"):
    PRReviewRecord.repo_full_name has a standalone index (ix_pr_review_records_repo_full_name
    defined in models.py). Filtering by repo_full_name uses that index efficiently.
    Without the index: full table scan across potentially thousands of reviews.

    PAGINATION PATTERN:
    We run two queries: one for the page of rows, one for the count.
    This is the standard offset-based pagination approach.
    Tradeoff: two queries per request. Acceptable because list_reviews()
    is a low-frequency operator/dashboard call, not a hot path.
    (DDIA Reliability-Scalability-Maintainability: "optimise for the common case.")

    NOTE ON FINDINGS LOADING:
    PRReviewRecord has lazy="selectin" on its findings relationship.
    For list views we do NOT want to load findings — they are fetched
    via get_review() in the detail view.
    However, selectin loading triggers automatically when the relationship
    is accessed. We simply do not access record.findings in the list path,
    so no extra query runs. The API converter (review_record_to_summary)
    uses len(record.findings) — this triggers one selectin per page batch,
    which SQLAlchemy batches into a single IN query (not N+1).

    Args:
        session:        SQLAlchemy AsyncSession
        repo_full_name: Optional filter — only reviews for this repo.
        status:         Optional filter — only reviews with this status string.
        limit:          Max rows to return (for pagination). Max 200.
        offset:         Row offset (for pagination).

    Returns:
        Tuple of (list of PRReviewRecord, total_count).
        total_count is the count matching the filters (ignoring limit/offset).
    """
    from sqlalchemy import func

    # Build the base WHERE conditions
    conditions = []
    if repo_full_name is not None:
        conditions.append(PRReviewRecord.repo_full_name == repo_full_name)
    if status is not None:
        conditions.append(PRReviewRecord.status == status)

    # Count query — same filters, no LIMIT/OFFSET
    count_result = await session.execute(
        select(func.count()).select_from(PRReviewRecord).where(*conditions)
    )
    total = count_result.scalar_one()

    # Data query — filtered, ordered, paginated
    data_result = await session.execute(
        select(PRReviewRecord)
        .where(*conditions)
        .order_by(PRReviewRecord.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    records = list(data_result.scalars().all())

    logger.debug(
        "list_reviews | repo=%s status=%s total=%d returned=%d",
        repo_full_name, status, total, len(records),
    )

    return records, total


# ---------------------------------------------------------------------------
# list_queue_items()
#
# Returns all reviews that are either:
#   a) In-flight (status is any non-terminal state), OR
#   b) Completed but flagged for human review (needs_human_review=1).
#
# This is the backing query for GET /api/v1/queue.
# ---------------------------------------------------------------------------
async def list_queue_items(
    session: AsyncSession,
    *,
    limit: int = 50,
    offset: int = 0,
) -> tuple[list[PRReviewRecord], int]:
    """
    Returns reviews that need attention: in-flight or awaiting human approval.

    QUEUE SEMANTICS:
    The queue shows two kinds of reviews:
      1. Active reviews (still running) — status NOT IN (completed, failed).
         These are: received, queued, in_progress, agents_running, aggregating, posting.
         Operators can see the pipeline is moving.
      2. Completed reviews that need human approval — status=completed AND
         needs_human_review=1. These are waiting for a HITL reviewer.
         (Phase 19 will add POST /queue/{id}/approve to act on them.)

    ORDERING: created_at ASC (oldest first).
    The HITL reviewer should process in arrival order — fairness for developers
    waiting for their PR review. (DDIA: "FIFO queues are fair by default.")

    WHY POSTGRES AND NOT ARQ?
    ARQ does not expose a "list pending jobs" query. Redis stores job payloads
    as opaque blobs in an LPUSH list — there is no way to filter or page them.
    Postgres is the authoritative state store. Once a job is picked up by the
    worker, it writes status=in_progress to Postgres. This is the correct place
    to query queue state. (DDIA: "durable state belongs in the authoritative store.")

    Args:
        session: SQLAlchemy AsyncSession
        limit:   Max rows to return.
        offset:  Row offset.

    Returns:
        Tuple of (list of PRReviewRecord, total_count).
    """
    from sqlalchemy import and_, func, or_

    # Terminal statuses — reviews in these states are NOT in the queue.
    # Reviews that failed are excluded (they need a different UI path, not the queue).
    terminal_statuses = ["completed", "failed"]

    # Condition: either still active (not terminal), or completed but pending human.
    # WIKI: Three-Gate-Approval-Pipeline (llmops-ai-agents)
    #   "Generation → Formal Validation → Human Approval"
    #   needs_human_review=1 means we are at the Human Approval gate.
    queue_condition = or_(
        PRReviewRecord.status.notin_(terminal_statuses),
        and_(
            PRReviewRecord.status == "completed",
            PRReviewRecord.needs_human_review == 1,
        ),
    )

    # Count query
    count_result = await session.execute(
        select(func.count()).select_from(PRReviewRecord).where(queue_condition)
    )
    total = count_result.scalar_one()

    # Data query — oldest first (FIFO processing order)
    data_result = await session.execute(
        select(PRReviewRecord)
        .where(queue_condition)
        .order_by(PRReviewRecord.created_at.asc())
        .limit(limit)
        .offset(offset)
    )
    records = list(data_result.scalars().all())

    logger.debug(
        "list_queue_items | total=%d returned=%d",
        total, len(records),
    )

    return records, total